ascii_control_codes = {
    b"\x00": "NUL (Null char)",
    b"\x01": "SOH (Start of Heading)",
    b"\x02": "STX (Start of Text)",
    b"\x03": "ETX (End of Text)",
    b"\x04": "EOT (End of Transmission)",
    b"\x05": "ENQ (Enquiry)",
    b"\x06": "ACK (Acknowledge)",
    b"\x07": "BEL (Bell)",
    b"\x08": "BS (Backspace)",
    b"\x09": "HT (Horizontal Tab)",
    b"\x0A": "LF (Line Feed)",
    b"\x0B": "VT (Vertical Tab)",
    b"\x0C": "FF (Form Feed)",
    b"\x0D": "CR (Carriage Return)",
    b"\x0E": "SO (Shift Out)",
    b"\x0F": "SI (Shift In)",
    b"\x10": "DLE (Data Link Escape)",
    b"\x11": "DC1 (Device Control 1)",
    b"\x12": "DC2 (Device Control 2)",
    b"\x13": "DC3 (Device Control 3)",
    b"\x14": "DC4 (Device Control 4)",
    b"\x15": "NAK (Negative Acknowledge)",
    b"\x16": "SYN (Synchronous Idle)",
    b"\x17": "ETB (End of Transmission Block)",
    b"\x18": "CAN (Cancel)",
    b"\x19": "EM (End of Medium)",
    b"\x1A": "SUB (Substitute)",
    b"\x1B": "ESC (Escape)",
    b"\x1C": "FS (File Separator)",
    b"\x1D": "GS (Group Separator)",
    b"\x1E": "RS (Record Separator)",
    b"\x1F": "US (Unit Separator)",
    b"\x7F": "DEL (Delete)",
}
